# Type stubs for the native ruLake module (rulake._rulake).
# These mirror src/lib.rs and are checked in CI via "build sdist, install,
# import, run mypy --strict over a smoke usage" (ADR-002 §Verification).

from __future__ import annotations
from os import PathLike
from typing import ClassVar, Optional, Union

import numpy as np
from numpy.typing import NDArray

__version__: str

# Type aliases. Vectors flow as float32 contiguous; ids as uint64.
_F32_1D = NDArray[np.float32]   # shape (D,)
_F32_2D = NDArray[np.float32]   # shape (N, D)
_U64_1D = NDArray[np.uint64]    # shape (N,)
_PathT  = Union[str, PathLike[str]]

# ─────────────────────────────────────────────────────────────────────
# Exceptions (also exported from the rulake/__init__.py with stdlib MI)
# ─────────────────────────────────────────────────────────────────────

class RuLakeError(Exception): ...
class BackendNotFoundError(RuLakeError): ...
class CollectionNotFoundError(RuLakeError): ...
class DimensionMismatchError(RuLakeError): ...
class InvalidParameterError(RuLakeError): ...
class BackendError(RuLakeError): ...

# ─────────────────────────────────────────────────────────────────────
# Consistency
# ─────────────────────────────────────────────────────────────────────

class Consistency:
    @classmethod
    def fresh(cls) -> "Consistency": ...
    @classmethod
    def eventual(cls, ttl_ms: int) -> "Consistency": ...
    @classmethod
    def frozen(cls) -> "Consistency": ...
    def __repr__(self) -> str: ...

# ─────────────────────────────────────────────────────────────────────
# Value classes
# ─────────────────────────────────────────────────────────────────────

class SearchResult:
    backend: str
    collection: str
    id: int        # u64 in Rust
    score: float   # f32 in Rust
    def as_tuple(self) -> tuple[str, str, int, float]: ...

class CacheStats:
    hits: int
    misses: int
    primes: int
    invalidations: int
    shared_hits: int
    total_prime_ms: float
    last_prime_ms: float
    warm_installs: int
    def hit_rate(self) -> Optional[float]: ...
    def avg_prime_ms(self) -> Optional[float]: ...

class PerBackendStats:
    hits: int
    misses: int
    primes: int
    invalidations: int
    shared_hits: int
    def hit_rate(self) -> Optional[float]: ...

# ─────────────────────────────────────────────────────────────────────
# Bundle (table.rulake.json)
# ─────────────────────────────────────────────────────────────────────

class Bundle:
    def __init__(
        self,
        data_ref: str,
        dim: int,
        rotation_seed: int,
        rerank_factor: int,
        generation: Union[int, str],
    ) -> None: ...
    @property
    def data_ref(self) -> str: ...
    @property
    def dim(self) -> int: ...
    @property
    def rotation_seed(self) -> int: ...
    @property
    def rerank_factor(self) -> int: ...
    @property
    def rvf_witness(self) -> str: ...
    @property
    def format_version(self) -> int: ...
    @property
    def pii_policy(self) -> Optional[str]: ...
    @property
    def lineage_id(self) -> Optional[str]: ...
    @property
    def memory_class(self) -> Optional[str]: ...
    @property
    def generation(self) -> Union[int, str]: ...
    def verify_witness(self) -> bool: ...
    def to_json(self) -> str: ...
    @classmethod
    def from_json(cls, s: str) -> "Bundle": ...
    def write_to_dir(self, dir: _PathT) -> str: ...
    @classmethod
    def read_from_dir(cls, dir: _PathT) -> "Bundle": ...
    def with_pii_policy(self, p: str) -> "Bundle": ...
    def with_lineage_id(self, id: str) -> "Bundle": ...
    def with_memory_class(self, class_: str) -> "Bundle": ...

# ─────────────────────────────────────────────────────────────────────
# Backends
# ─────────────────────────────────────────────────────────────────────

class LocalBackend:
    def __init__(self, id: str) -> None: ...
    @property
    def id(self) -> str: ...
    def put_collection(self, name: str, ids: _U64_1D, vectors: _F32_2D) -> None: ...
    def append(self, collection: str, id: int, vector: _F32_1D) -> None: ...

class FsBackend:
    def __init__(self, id: str, root: _PathT) -> None: ...
    def register(self, collection: str, filename: str) -> None: ...
    def write(
        self,
        collection: str,
        filename: str,
        ids: _U64_1D,
        vectors: _F32_2D,
    ) -> str: ...

# ─────────────────────────────────────────────────────────────────────
# RuLake
# ─────────────────────────────────────────────────────────────────────

class RuLake:
    def __init__(self, rerank_factor: int = 20, rotation_seed: int = 42) -> None: ...
    def with_consistency(self, c: Consistency) -> "RuLake": ...
    def with_max_cache_entries(self, n: int) -> "RuLake": ...
    def register_backend(self, backend: Union[LocalBackend, FsBackend]) -> None: ...
    def backend_ids(self) -> list[str]: ...
    def cache_stats(self) -> CacheStats: ...
    def cache_stats_by_backend(self) -> dict[str, PerBackendStats]: ...
    def cache_entry_count(self) -> int: ...
    def cache_witness_of(self, backend: str, collection: str) -> Optional[str]: ...
    def invalidate_cache(self, backend: str, collection: str) -> None: ...
    def search_one(
        self, backend: str, collection: str, query: _F32_1D, k: int
    ) -> list[SearchResult]: ...
    def search_federated(
        self, targets: list[tuple[str, str]], query: _F32_1D, k: int
    ) -> list[SearchResult]: ...
    def search_batch(
        self, backend: str, collection: str, queries: _F32_2D, k: int
    ) -> list[list[SearchResult]]: ...
    def search_one_arrays(
        self, backend: str, collection: str, query: _F32_1D, k: int
    ) -> tuple[_U64_1D, _F32_1D]: ...
    def publish_bundle(
        self, backend: str, collection: str, dir: _PathT
    ) -> str: ...
    def refresh_from_bundle_dir(
        self, backend: str, collection: str, dir: _PathT
    ) -> str: ...  # "up_to_date" | "invalidated" | "bundle_missing"
    def save_cache_to_dir(
        self, backend: str, collection: str, dir: _PathT
    ) -> str: ...
    def warm_from_dir(
        self, backend: str, collection: str, dir: _PathT
    ) -> int: ...
